---
- name: Install packages
  hosts: dev, prod
  become: true
  tasks:
  - name: install listed packages on all hosts
    yum:
      name:
      - httpd
      - mod_ssl
      - mariadb
      state: present
  - name: Install dev tools on dev hosts
    yum:
      name: 
      - "@Development"
      state: present
    when: "'dev' in group_names"
  - name: Update all packages on dev hosts only
    yum:
      name: '*'
      state: latest
    when: "'dev' in group_names"