---
- name: copy file and populate
  hosts: all
  tasks:
    - name: copy out specs file
      copy: 
        src: specs.empty
        dest: /tmp/specs.txt
   
    - name: add in hostname info
      lineinfile:
        regex: ^HOST
        line: HOST={{ansible_hostname}}
        state: present
        path: /tmp/specs.txt
    - name: add in memory info
      lineinfile:
        regex: ^MEMORY
        line: MEMORY={{ansible_memtotal_mb}}
        state: present
        path: /tmp/specs.txt
    - name: add in bios info
      lineinfile:
        regex: ^BIOS
        line: BIOS={{ansible_bios_version}}
        state: present
        path: /tmp/specs.txt
    - name: add in vda size
      lineinfile:
        regex: ^VDA_DISK_SIZE
        line: VDA_DISK_SIZE={%if ansible_devices.nvme0n1 is defined%}{{ansible_devices.nvme0n1.size}}{%else%}NONE{%endif%}
        state: present
        path: /tmp/specs.txt
    - name: add in my vda size to vdb
      lineinfile:
        regex: ^VDB_DISK_SIZE
        line: VDB_DISK_SIZE={%if ansible_devices.nvme0n2 is defined%}{{ansible_devices.nvme0n2.size}}{%else%}NONE{%endif%}
        state: present
        path: /tmp/specs.txt
    
    - name: Return the file output
      shell: cat /tmp/specs.txt
      register: content
    - name: print file contents
      debug:
        var: content.stdout_lines