--- 
- name: "install haproxy and php roles on hosts"
  hosts: all
  tasks: 
    - include_role:
        name: "haproxy-role"
      when: "'proxy' in group_names"
    - include_role:
        name: php_role
      when: "'prod' in group_names"
  vars: 
    haproxy_backend_servers: 
      - name: web1 
        address: "ansible1.example.com:80"
      - name: web2
        address: "ansible2.example.com:80"
        
