---
- name: Create a directory and set permissions to allow for it to served by httpd
  hosts: ansible2
  tasks:
    - name: Create webdev user
      user:
        name: webdev
        state: present
    - name: Create a directory
      file:
        mode: '2755'
        path: /webdev
        owner: webdev
        group: webdev
        state: directory
    - name: Create a symlink to it
      file:
        src: /webdev
        path: /var/www/html/webdev
        state: link
    - name: Create index.html
      copy:
        content: Development
        dest: /webdev/index.html
    - name: install selinux policies
      yum:
        name: python3-policycoreutils
        state: present
    - name: allow http to this directory
      sefcontext:
        target: '/webdev(/.*)?'
        setype: httpd_sys_content_t
        state: present
    - name: restore the content
      shell: restorecon -Rv /webdev
    - name: restart httpd
      service:
        name: httpd
        state: restarted