---
- name: Setup storage on different servers
  hosts: all
  tasks:
  - name: Print No Second Disk Message
    debug:
      msg: "No Second Disk found"
    when:
      - ansible_facts['ansible_devices']['nvme0n2'] is not defined
  - name: create LV on > 1G
    block:
      - name: Create 1500 partition
        parted:
          device: /dev/nvme0n2
          number: 1
          part_end: 1.8GiB
          state: present

      - name: Create Vol Group
        lvg:
          pvs: /dev/nvme0n2p1
          vg: vgdata
          state: present
      - name: Create LV
        lvol:
          vg: vgdata
          lv: lvdata
          size: 1.5g
          state: present
      - name: create File System
        filesystem:
          dev: /dev/vgdata/lvdata
          fstype: xfs
    when:  
      - ansible_facts['devices']['nvme0n2']  is defined
      - ansible_facts['devices']['nvme0n2']['size']  > "1000000"
        
  - name: create LV on > 1G
    block:
      - name: Display message
        debug:
          msg: Small disk found
      - name: Create 800M LV
        parted:
          device: /dev/nvme0n2
          number: 1
          part_end: 900MiB
          state: present

      - name: Create Vol Group
        lvg:
          pvs: /dev/nvme0n2p1
          vg: vgdata
          state: present
      - name: Create LV
        lvol:
          vg: vgdata
          lv: lvdata
          size: 800m
          state: present
      - name: create File System
        filesystem:
          dev: /dev/vgdata/lvdata
          fstype: xfs
    when:  
      - ansible_facts['devices']['nvme0n2']  is defined
      - ansible_facts['devices']['nvme0n2']['size']  <= "1000000"
