---
- name: create storage
  hosts: ansible2
  tasks:
  - name: create new partition
    parted:
      #name: files
      #label: gpt
      device: /dev/nvme0n2
      number: 1
      flags: [ lvm ]
      state: present
      #part_start: 1MiB
      #part_end: 2GiB